apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: grv6uzqx7-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:bd868dc7b9538e2b83950fa8293381d8a975093b@sha256:9777a7297d1851887ec3ab561880db55ba641e2a5de9dc0ce1ca6c5990ae3a2c
          name: container-image
